Repository insightsengineering/teal.gallery, pull requests merged in 2023-08, with the labels that each got.

#35 34 remove formatters
  early-dev/app.R
  efficacy/app.R
  longitudinal/app.R
  patient-profile/app.R
  safety/app.R
Labels: core

#46 Rename the deprecated function argument `filters`
  early-dev/app.R
Labels: core

#45 Set up initial seed for `longitudinal` app for reproducibility
  longitudinal/app.R
Labels: core

#48 47 `python` add rounding of values allowing for reproducible code
  python/app.R
Labels: bug, core

#58 Make all the demo apps consistent with same footer and front page
  RNA-seq/app.R
  basic-teal/app.R
  early-dev/app.R
  efficacy/app.R
  exploratory/app.R
  longitudinal/app.R
  patient-profile/app.R
  python/app.R
  safety/app.R
Labels: core

#59 Add consistent titles, favicon and nest logo to the apps
  RNA-seq/app.R
  RNA-seq/www/favicon.ico
  RNA-seq/www/nest.png
  basic-teal/app.R
  basic-teal/www/favicon.ico
  basic-teal/www/nest.png
  early-dev/app.R
  early-dev/www/favicon.ico
  early-dev/www/nest.png
  efficacy/app.R
  efficacy/www/favicon.ico
  efficacy/www/nest.png
  exploratory/app.R
  exploratory/www/favicon.ico
  exploratory/www/nest.png
  longitudinal/app.R
  longitudinal/www/favicon.ico
  longitudinal/www/nest.png
  patient-profile/app.R
  patient-profile/www/favicon.ico
  patient-profile/www/nest.png
  python/app.R
  python/www/favicon.ico
  python/www/nest.png
  safety/app.R
  safety/www/favicon.ico
  safety/www/nest.png
Labels: core

#61 Reorder the demo apps based on increasing complexity
  README.md
  _internal/quarto/demo-apps.yml
Labels: core

#60 Play the gif only on hover and show static image when non hovered
  README.md
  _internal/quarto/assets/img/RNA-seq.gif
  _internal/quarto/assets/img/RNA-seq.png
  _internal/quarto/assets/img/basic-teal.gif
  _internal/quarto/assets/img/basic-teal.png
  _internal/quarto/assets/img/early-dev.gif
  _internal/quarto/assets/img/early-dev.png
  _internal/quarto/assets/img/efficacy.gif
  _internal/quarto/assets/img/efficacy.png
  _internal/quarto/assets/img/exploratory.gif
  _internal/quarto/assets/img/exploratory.png
  _internal/quarto/assets/img/longitudinal.gif
  _internal/quarto/assets/img/longitudinal.png
  _internal/quarto/assets/img/patient-profile.gif
  _internal/quarto/assets/img/patient-profile.png
  _internal/quarto/assets/img/python.gif
  _internal/quarto/assets/img/python.png
  _internal/quarto/assets/img/safety.gif
  _internal/quarto/assets/img/safety.png
  _internal/quarto/assets/style.scss
  _internal/quarto/demo-template.ejs
Labels: core, priority

#63 Remove acronyms for example app code
  longitudinal/app.R
Labels: core, priority
