Repository insightsengineering/teal.gallery, pull requests merged in 2024-03, with the labels that each got.

#151 3 load specific scda data
  RNA-seq/app.R
  early-dev/app.R
  efficacy/app.R
  exploratory/app.R
  longitudinal/app.R
  patient-profile/app.R
  safety/app.R
Labels: core

#153 Dev@main
  RNA-seq/app.R
  early-dev/app.R
  efficacy/app.R
  exploratory/app.R
  longitudinal/app.R
  patient-profile/app.R
  safety/app.R
Labels: core

#155 Include the dev app deployments link in the readme
  README.md
Labels: documentation, core

#158 Fix app deployments
  .github/workflows/deploy.yml
Labels: bug, core

#168 Install released version of tmg in the stable deployments
  .github/workflows/deploy.yml
  RNA-seq/renv.lock
  early-dev/renv.lock
  efficacy/renv.lock
  exploratory/renv.lock
  longitudinal/renv.lock
  patient-profile/renv.lock
  python/renv.lock
  safety/renv.lock
Labels: core
