Repository insightsengineering/teal.gallery, pull requests merged in 2024-02, with the labels that each got.

#136 135 fix data in `nest_basic_teal` app
  basic-teal/app.R
Labels: bug, core

#141 Capitalize Patient Profile app labels
  patient-profile/app.R
Labels: core, sme

#147 Merge `dev` on `main`
  .github/workflows/deploy.yml
  .gitlab-ci.yml
  .lintr
  RNA-seq/app.R
  RNA-seq/renv.lock
  basic-teal/app.R
  basic-teal/renv.lock
  early-dev/app.R
  early-dev/renv.lock
  efficacy/app.R
  efficacy/renv.lock
  efficacy/renv/activate.R
  exploratory/app.R
  exploratory/renv.lock
  longitudinal/app.R
  longitudinal/renv.lock
  longitudinal/renv/activate.R
  longitudinal/tests/cypress/e2e/app.cy.js
  patient-profile/app.R
  patient-profile/renv.lock
  patient-profile/renv/activate.R
  python/app.R
  python/renv.lock
  safety/app.R
  safety/renv.lock
  safety/renv/activate.R
Labels: core

#150 Install tmc from CRAN
  .github/workflows/deploy.yml
  early-dev/renv.lock
  efficacy/renv.lock
  longitudinal/renv.lock
  patient-profile/renv.lock
  safety/renv.lock
Labels: core
